:linkGettingStarted: TODO
:linkTroubleshooting: TODO
:linkGitHubFork: https://help.github.com/articles/fork-a-repo/
:linkIndexURL: TODO

= Publishing Walkthroughs to a cluster

Add to the catalog of walkthroughs in your environment.

In addtition to the default walkthroughs, you can import existing walkthroughs from a git repository.

NOTE: You must have access to the link:{openshift-host}[OpenShift Console].


[type=walkthroughResource]
.Links
****
* link:{linkGettingStarted}[Getting Started]
* link:{linkTroubleshooting}[Troubleshooting]
****

:sectnums:

[time=10]
== Finding walkthroughs

Walkthroughs are available from git repositories, typically hosted on GitHub or GitLab. 

A git repository typically contains many walkthroughs.

See the link:{linkIndexURL}[index of walkthrough repositories] for more information.

=== Forking walkthrough repos

To have precise control over what is published in your environment, create a fork of the git repository you want to use. This allows you to:

* delete walkthroughs before publication
* add additional walkthroughs that you have written

. Log into the git hosting service.
. Navigate to the repository you want to fork.
. Fork the repository using the instructions from the git hosting service, for example, link:{linkGitHubFork}[GitHub instructions].

[type=verification]
You have the URL one or more repositories with the exact content you want to publish. 

[type=verificationFail]
Continue searching, new walkthroughs are created on GitHub monthly and the link:{linkIndexURL}[index of walkthrough repositories] is updated. 

[time=10]
== Publishing the Walkthrough in the Webapp

You can add repositories containing one or more Walkthroughs to a Webapp deployed to Openshift.

=== Adding the template repository to the Webapp

For each repository URL that you have from Task 1:

. Open the link:{openshift-host}[Openshift Console].

. Find and open the *webapp* project.

. Find and open the *tutorial-web-app* deployment.

. Select the *Environment* tab.

. Note the value of the environment variable with the name *WALKTHROUGH_LOCATIONS*, by default it is:
+
----
https://github.com/integr8ly/tutorial-web-app-walkthroughs.git
----
+
The walkthroughs in this repo must always be available in the environment. 

. Append your repository URL to the value of that variable, separated by a comma, and click *Save*. For example:
+
----
https://github.com/integr8ly/tutorial-web-app-walkthroughs.git,https://github.com/integr8ly/example-customisations.git#master
----
+
NOTE: Make sure there are no space characters in the value of the *WALKTHROUGH_LOCATIONS* environment variable. 
+
Editing the value triggers an automatic redeployment of the Webapp.

. When the deployment is complete, refresh the Webapp in your Browser.
+
You should now see new walkthroughs available from the dashboard.

[type=verification]
Make sure that you can see a Walkthrough with the title *My first Walkthrough* in the dasboard.

[type=verificationFail]
Check that the Webapp has finished redeployment and no errors occurred.
