// tag::master-1[]

:walkthrough: No code API development and SaaS integration
:fuse-version: 7.2
:3scale-version: 7.2
:fuse-url: https://eval.apps.city.openshiftworkshop.com/
:3scale-url: https://eval.apps.city.openshiftworkshop.com/

[id='no-code-container-native-api-development']

= {walkthrough}

This walkthrough demonstrates how to implement a container-native OpenAPI RESTful API without coding.

Container-native applications::
Applications that are designed to run in a containerised environment.

// This is taken right from https://github.com/OAI/OpenAPI-Specification
OpenAPI Specification::
A standard, programming language-agnostic interface description for REST APIs, which allows both humans and computers to discover and understand the capabilities of a service without requiring access to source code, additional documentation, or inspection of network traffic. When properly defined via OpenAPI, a consumer can understand and interact with the remote service with a minimal amount of implementation logic.

In this walkthrough you follow a design-first approach, based on the OpenAPI specification, to define a RESTful API that accepts a name parameter and echoes it back in the response body. 
You then use the resulting Open API definition to generate the code for your API and deploy it in a containerised environment.

Following a design first approach to API development is self-documenting, and provides a clear API definition for partners and end-users of your API.
It also allows you to identify important design decisions prior to coding and deployment.

[type=walkthroughResource,serviceName=fuse]
.Fuse Online
****
* link:{fuse-url}[Console, window="_blank"]
****

[type=walkthroughResource,serviceName=openshift]
.Red Hat OpenShift
****
* link:{openshift-host}/console[Console, window="_blank"]
****

[type=walkthroughResource,serviceName=3scale]
.3Scale
****
* link:{api-management-url}[Console, window="_blank"]
* link:https://developers.redhat.com/products/3scale/overview/[3Scale Overview, window="_blank"]
* link:https://www.3scale.net[3Scale Website, window="_blank"]
****


[time=10]
== Creating a Slack Connection in Fuse Online

In Fuse Online a *Connection* holds the information required to connect to a service.
For example, a Slack *Connection* in Fuse Online requires an *API Token* and *Slack URL* to function. 

=== Creating a Slack Workspace

.Prerequisite
You already have an account with link:https://slack.com/[Slack].

If you already have admin access to a Slack workspace, skip this procedure.

. Navigate to the link:https://slack.com/create[Create a new workspace, window="_blank"] page.

. Enter your email address and click *Next*.

. Enter the following name for your workspace and click *Next*:
+
----
low-code-workspace
----
+
The name you choose becomes part of the URL for the workspace. 

. When prompted *What is your team working on?* enter:
+
----
low-code-demo
----

. Click *Skip for now* when prompted to add team members.

// verify that you can access https://your-workspace-name-guid.slack.com.
[type=verification]
Can you access your workspace, and navigate to the *low-code-demo* channel listed on the left of the workspace?


[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact Slack support.


=== Creating the Slack Connection in Fuse Online

. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank"] console.
+
NOTE: This is your personal Fuse Online instance and not the shared instance available from link:/[home page].

. Choose *Connections* from the left navigation menu.

. Click the *Create Connection* button in the top right corner.

. Choose *Slack* from the list of displayed *Connectors*. 
You are prompted for configuration details.

. Obtain a URL for the *Slack Webhook URL* field:
.. Navigate to the Slack Apps portal at link:https://api.slack.com/apps[api.slack.com/apps].
.. Login using the email address associated with your workspace.
.. Click *Create new App*.
.. Enter the following in the *App Name* field:
+
----
Fuse Online Demo
----
.. Choose *low-code-workspace* from the *Development Slack Workspace* menu.
.. Click "Create App".
.. On the following screen under the *Add features and functionality* click *Incoming Webhooks*.
.. Change the *Activate Incoming Webhooks* switch to the *On* position.
.. Scroll down and click *Add New Webhook to Workspace*.
.. In the *Post to* field select *low-code-demo* and click *Install*.
+
You are redirected back to the *Incoming Webhooks* page. 
.. Copy the *Webhook URL* displayed at the bottom of the page using the *Copy* button. 

. Paste the copied *Webhook URL* value into the *Slack Webhook URL* field in Fuse Online.

. Obtain a value for the *Token for Accessing Slack API* field:
.. Navigate to the Slack API Token portal at link:https://api.slack.com/custom-integrations/legacy-tokens[api.slack.com/custom-integrations/legacy-tokens, window="_blank"].
.. Login using the email address associated with your workspace.
.. Scroll down to the *Legacy token generator* section.
.. Click *Create token* button next to a workspace you own, or have admin rights for.
.. Copy the generated token.

. Paste the generated token into the *Token for Accessing Slack API* field in Fuse Online.

. Enter the following in the *Sending User Name for Messages* field:
+
----
Fuse Online
----

. Click *Validate* in Fuse Online and verify that a *Slack has been successfully validated.* message appears. Click *Next*.

. Enter the following in the *Connection Name* field on the *Add Connection Details* screen:
+
----
Greeting Slack Target
----

. Click *Create*.

[type=verification]
Is a *Greeting Slack Target* entry listed in the Fuse Online *Connections* screen?


[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.

[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.

[time=10]
== Creating an API Integration in Fuse Online

=== Creating an Integration with API details

In this procedure, you create an integration with an API and include a data type.
A *Data Type* represents a data structure that can be passed to your API and can then be used as parameters in your API definition and within the Fuse Online *Integration Flow Editor* to transform and map data as part of an *Integration*.


. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank"] console.

. Select *Integrations* from the left hand menu.

. Click the *Create Integration* button to start the *New Integration* wizard.

. Choose *API Provider* on the subsequent *Choose a Start Connection* screen.

. When prompted choose *Create from scratch* and click *Next* to navigate to the *API Designer*.

. Rename your API from "Untitled API" to:
+
----
Greeting API
----

. Edit the *Description*:
+
----
My greeting API
----

. Click *Add a data type* under the *Data Types* heading on the left of the *API Designer* screen.

. In the *Enter Basic Information* section enter the following in the *Name* field:
+
----
Name
----

. Enter the following JSON in the *Enter JSON Example* field:
+
[subs="attributes+"]
----
{
    "name": "shadowman" 
}
----

. Under the *Create a REST Resource* section choose *No Resource*.

. Click *Save*.

[type=verification]
Is `</> Name` listed under the *Data Types* on the *API Designer* screen?


[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.


=== Creating a POST Resource Path

A *Path* represents an API endpoint/operation and the associated parameters required to invoke it.

. Click *Add a path* under the *Paths* heading on the left of the *API Designer* screen.

. In the modal that appears, enter the following in the *Path* field:
+
----
/greeting
----

. Click *Add* to confirm your entry.

. Click your new */greeting* endpoint under the *Paths* heading.

. Select the *POST* tab under the *Operations* section on the right.

. Click the *Add Operation* button within the *POST* section. A set of fields will appear. 

. Enter the following in the *Summary* field:
+
----
Greet with name
----

. Enter the following in the *Operation ID* field:
+
----
greetname
----

. In the *Request Body* section click *Add a request body* and choose the *Name* type that you created earlier.

. In the *Responses* section click *Add response*.
.. In the modal that appears choose *200 OK* as the status code dropdown option.
.. Click *Add*.
.. Click *No description* beside the *200 OK* response and enter the following in the *Description* field:
+
----
Greeting response
----

. Select *String* as *String* in the *Response Type* dropdown.

. Click *Save* in the top right corner of the UI to save your work and be directed back to the *Review Actions* wizard.

. Click *Next* on the *Review Actions* screen.

. When prompted to *Give this integration a name*:
.. Enter the following in the *Integration Name* field:
+
----
greeting api
----
.. Enter the following in the *Description* field:
+
----
my greeting api
----

. Click *Save and Continue* to save your API design.


[type=verification]
Is the *API Provider Integration* screen displaying your *POST /greeting* operation?

[type=verificationFail]
Choose *View/Edit API Definition* and repeat the steps above to create the *POST* endpoint.


[time=10]
== Implementing and publishing the API

. On the *API Provider Integration* screen click *Greet with name* to open the *Integration Flow Editor*.

. The left hand side of the *Integration Flow Editor* lists the steps in your *Integration*. Hover mouse over the *Blue Plus Icon* in the center of the flow and choose *Add Connection*.

. Select your *Greeting Slack Target*.

. When prompted to *Choose an action* select *Channel*. You can use this to send a mesasge to a specific channel in your Slack workspace.

. Use the *Channel* dropdown to select the *low-code-project* channel and click *Done*.
The left hand side of the *Integration Flow Editor* should now list your Slack connection with a *Data Type Mismatch* warning. 

. Click the *Data Type Mismatch* warning icon and choose *Add a data mapping step* in the dialog box that is displayed.

. From the *Configure Mapper* panel click the *body* element under *Request* in the *Source* panel to expand it.

. Click the *name* field inside the *body*, then click the *message* element in the *Target* panel. This maps the value of the incoming HTTP request *body* to the outgoing Slack *message* property.

. In the right hand *Mapping Details* panel click the *Arrow Icon* under the *Targets* section to add a transformation.

. Using the dropdown change the transformation type from *Append* to *Prepend*.

. Enter the following in the *string* field under the dropdown:
+
----
Hello from 
----

. Click *Done*.

. On the left side of the *Integration Flow Editor* a new *Data Type Mismatch* is highlighted on the *Provided API Return Path*. Click it and choose *Add a data mapping step*.

. From the *Configure Mapper* panel choose *message* under the *Data Mapper (Message)* section and link it to the *name* field under *body* on the right.

. Click *Done*.

. Click *Publish* to trigger an link:https://docs.openshift.com/container-platform/3.11/creating_images/s2i.html[Source to Image (S2I), window="_blank"] build.

. Wait until Fuse Online reports your deployment was successful.

[type=verification]
Does the Fuse Online *Home* screen list your *greeting api* with a blue box that contains the text *Running*?


[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.



[time=10]
== Exposing and invoking the API

=== API Management Login

. Open the link:{api-management-url}[{3Scale-ProductName} Login screen, window="_blank"].

. Select the *Red Hat Single Sign On* option. This triggers an OAuth Flow and redirects you back to the {3Scale-ProductName} Dashboard.

. Dismiss the *How does 3Scale work?* option which is displayed the first time you log in to {3Scale-ProductName}. The main Dashboard is displayed.

[type=verification]
Can you see the {3Scale-ProductName} Dashboard and navigate the main menu?

[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.


=== Adding the App Endpoint to Red Hat 3scale

. From the *Dashboard*, select the *New API* item.
. Select the *Import from Dashboard* option.
If this option is not enabled, click *authenticate with OpenShift* to enable the option.

. Choose the 'fuse' option from the *Namespace* list.
. Choose 'i-greeting-api' from the *Name* list.
. Click *Create Service*.
+
The 3scale dashboard is displayed, with notification: `The service will be imported shortly. You will receive a notification when it is done.`

. Edit the API Service:

.. From the top navigation bar click the dropdown and choose your 'i-greeting-api'

.. From the *Overview* screen, select the *Configure APIcast* button.

.. In the *Staging Public Base URL*, enter:
+
[subs="attributes+"]
----
https://wt-{user-sanitized-username}-3scale.{openshift-app-host}
----
+
If the wildcard proxy is enabled in your cluster, this route points to the wildcard APIcast URL. Otherwise, the route points to the shared staging APIcast URL for the *3scale* project in OpenShift

[NOTE]
====
If you have previously used the ```https://wt-{user-sanitized-username}-3scale.{openshift-app-host}``` route, that service is no longer available.
For example, if you have completed the *Managing and protecting APIs using API management* walkthrough, that API is no longer available because you have reused the route.
====

.. Expand the *Mapping Rules* section and click the pencil icon to edit the default entry.

.. Change *Verb* to *POST* and *Pattern* to */greeting*.

.. Scroll down to the *Client* section. This section enables 3scale to test connectivity to our API via the gateway. Since our API does not expose a *GET* endpoint we won't be using it, but note that the *user_key* is this section is currently not set to an actual value. To fix this we need to create an *Application Plan* for our *API Service* and an *Application*.

.. Click *Update & test in Staging Environment* to save your changes.


. Create An Application Plan

.. Click *Overview* to return to the overview screen for your API.

.. Click *Create Application Plan* in the *Published Application Plans* section.

.. Enter the following name:
+
----
Greeting API Application Plan
----

Enter the following system name:
+
----
greeting-app-plan
----

.. Ensure the *Applications require approval?* box is not ticked, then click *Create Application Plan*.


. Create an Application

.. Navigate to *Audience* using the dropdown in the top navigation bar.

.. Choose *Developer* from the account listing.

.. In the breadcrumb bar click *$NUMBER Application* link next to your account name to view applications.

.. Click *Create Application* at the top of the displayed list.

.. On the *New Application* screen choose your *Greeting API Application Plan* in the *Application Plan* dropdown.

.. Enter the following name:
+
----
Greeting Application
----

Enter the following description:
+
----
Greeting Application that sends greetings to Slack
----

=== Invoking the API

.. From your new *Greeting Application* screen click the *i-greeting-api* next to Service.

.. From the *Overview* screen click *Configuration* and choose *edit APIcast configuration* on the displayed *Configuration* page.

.. Scroll down and note that the *user_key* parameter is now set.

.. Using the URL we can execute a cURL request from a terminal with the command below. You can use a tool such as Postman if you prefer. Make sure you replace *$YOUR_KEY* with the key displayed in 3scale:
+
----

curl -X POST -H 'content-type: application/json' --data '{"name":"{user-sanitized-username}"}' "https://wt-{user-sanitized-username}-3scale.{openshift-app-host}/greeting?user_key=$YOUR_KEY"
----

[type=verification]
Did the message "Hello from {{user-sanitized-username}" appear in your Slack channel?

[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.
