// tag::master-1[]

:walkthrough: No code API development and SaaS integration
:fuse-version: 7.2
:3scale-version: 7.2
:fuse-url: https://eval.apps.city.openshiftworkshop.com/
:3scale-url: https://eval.apps.city.openshiftworkshop.com/

[id='no-code-container-native-api-development']

= {walkthrough}

This walkthrough demonstrates how to implement a container-native OpenAPI RESTful API without coding.

Container-native applications::
Applications that are designed to run in a containerised environment.

// This is taken right from https://github.com/OAI/OpenAPI-Specification
OpenAPI Specification::
A standard, programming language-agnostic interface description for REST APIs, which allows both humans and computers to discover and understand the capabilities of a service without requiring access to source code, additional documentation, or inspection of network traffic. When properly defined via OpenAPI, a consumer can understand and interact with the remote service with a minimal amount of implementation logic.

In this walkthrough you follow a design-first approach, based on the OpenAPI specification, to define a RESTful API that accepts a name parameter and echoes it back in the response body. 
You then use the resulting Open API definition to generate the code for your API and deploy it in a containerised environment.

Following a design first approach to API development is self-documenting, and provides a clear API definition for partners and end-users of your API.
It also allows you to identify important design decisions prior to coding and deployment.

[type=walkthroughResource,serviceName=fuse]
.Fuse Online
****
* link:{fuse-url}[Console, window="_blank"]
****

[type=walkthroughResource,serviceName=3scale]
.3Scale
****
* link:{api-management-url}[Console, window="_blank"]
* link:https://developers.redhat.com/products/3scale/overview/[3Scale Overview, window="_blank"]
* link:https://www.3scale.net[3Scale Website, window="_blank"]
****

[type=walkthroughResource,serviceName=openshift]
.Red Hat OpenShift
****
* link:{openshift-host}/console[Console, window="_blank"]
****

// end::master-1[]

[time=10]
== Creating a Slack Connection in Fuse Online

In Fuse Online a *Connection* holds the information required to connect to a service.
For example, a Slack *Connection* in Fuse Online requires an *API Token* and *Slack URL* to function. 

=== Creating a Slack Workspace

.Prerequisite
You already have an account with link:https://slack.com/[Slack].

If you already have admin access to a Slack workspace, skip this procedure.

. Navigate to the link:https://slack.com/create[Create a new workspace, window="_blank"] page.

. Enter your email address and click *Next*.

. Enter the following name for your workspace and click *Next*:
+
----
low-code-workspace
----
+
The name you choose becomes part of the URL for the workspace. 

. When prompted *What is your team working on?* enter:
+
----
Low-code Demo
----

. Click *Skip for now* when prompted to add team members.

// verify that you can access https://your-workspace-name-guid.slack.com.
[type=verification]
Can you access your workspace, and navigate to the *low-code-project* channel listed on the left of the workspace?


[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact Slack support.


=== Creating the Slack Connection in Fuse Online

. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank"] console.
+
NOTE: This is your personal Fuse Online instance and not the shared instance available from link:/[home page].

. Choose *Connections* from the left navigation menu.

. Click the *Create Connection* button in the top right corner.

. Choose *Slack* from the list of displayed *Connectors*. 
You are prompted for configuration details.

. Obtain a URL for the *Slack Webhook URL* field:
.. Navigate to the Slack Apps portal at link:https://api.slack.com/apps[api.slack.com/apps].
.. Login using the email address associated with your workspace.
.. Click "Create new App".
.. Enter "Fuse Online Demo" in the *App Name* field.
.. Choose your workspace using the *Development Slack Workspace* dropdown.
.. On the following screen under the *Add features and functionality* click *Incoming Webhooks*.
.. Change the *Activate Incoming Webhooks* switch to the *On* position.
.. Scroll down and click *Add New Webhook to Workspace*.
.. In the *Post to* field select the *low-code-project* or a channel of your own choosing then click *Authorise*.
.. When redirected back to the *Incoming Webhooks* copy the new *Webhook URL* displayed at the bottom of the page using the *Copy* button. 

. Paste the copied *Webhook URL* value into the *Slack Webhook URL* field in Fuse Online.

. Obtain a value for the *Token for Accessing Slack API* field:
.. Navigate to the Slack API Token portal at link:https://api.slack.com/custom-integrations/legacy-tokens[api.slack.com/custom-integrations/legacy-tokens, window="_blank"].
.. Login using the email address associated with your workspace.
.. Scroll down to the *Legacy token generator* section.
.. Click *Create token* button next to a workspace you own, or have admin rights for.
.. Copy the generated token.

. Paste the generated token into the *Token for Accessing Slack API* field in Fuse Online.

. Enter the following in the *Sending User Name for Messages* field:
+
----
Fuse Online
----

. Click *Validate* in Fuse Online and verify that a *Slack has been successfully validated.* message appears. Click *Next*.

. Enter the following in the *Connection Name* field on the *Add Connection Details* screen:
+
----
Greeting Slack Target
----

. Click *Create*.

[type=verification]
Is a *Greeting Slack Target* entry listed in the Fuse Online *Connections* screen?


[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.

[time=10]
== Creating an API Integration in Fuse Online

=== Creating an Integration with API details

In this procedure, you create an integration with an API and include a data type.
A *Data Type* represents a data structure that can be passed to your API and can then be used as parameters in your API definition and within the Fuse Online *Integration Flow Editor* to transform and map data as part of an *Integration*.

. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank"] console.

. Select *Integrations* from the left hand menu.

. Click the *Create Integration* button to start the *New Integration* wizard.

. Choose *API Provider* on the subsequent *Choose a Start Connection* screen.

. When prompted choose *Create from scratch* and click *Next* to navigate to the *API Designer*.

. Rename your API from "Untitled API" to:
+
----
Greeting API
----

. Edit the *Description*:
+
----
My greeting API
----

. Click *Add a data type* under the *Data Types* heading on the left of the *API Designer* screen.

. In the *Enter Basic Information* section enter the following in the *Name* field:
+
----
Name
----

. Enter the following JSON in the *Enter JSON Example* field:
+
[subs="attributes+"]
----
{
    "name": "shadowman" 
}
----

. Scroll down and click *Save*.

[type=verification]
Is `</> Name` listed under the *Data Types* on the *API Designer* screen?


[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.


=== Creating a POST Resource Path

A *Path* represents an API endpoint/operation and the associated parameters required to invoke it.

. Click *Add a path* under the *Paths* heading on the left of the *API Designer* screen.

. In the modal that appears, enter the following in the *Path* field:
+
----
/greeting
----

. Click *Add* to confirm your entry.

. Click your new */greeting* endpoint under the *Paths* heading.

. Click *Create Operation* under the *POST* icon in the *Operations* section on the right. The *POST* icon changes to an orange color.

. Click the orange *POST* icon.

. Enter the following in the *Summary* field:
+
----
Greet with name
----

. Enter the following in the *Operation ID* field:
+
----
greetname
----

. In the *Request Body* click *Add a request body* and choose the *Name* type that you created earlier.

. In the *Responses* section click *Add response*.
.. In the modal that appears choose *200 OK* as the dropdown option.
.. Click *Add*.
.. Click *No description* beside the *200 OK* response and enter the following in the *Description* field:
+
----
Greeting response
----

. Click *Save* in the top right corner of the UI to save your work and be directed back to the *New Integration* wizard.

. Click *Next* on the *New Integration* wizard screen.

. When prompted to *Give this integration a name*:
.. Enter the following in the *Integration Name* field:
+
----
greeting api
----
.. Enter the following in the *Description* field:
+
----
my greeting api
----

. Click *Save and Continue* to save your API design.


[type=verification]
Is a *Greeting Slack Target* entry is listed in the Fuse Online *Connections* screen?

[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.


[time=10]
== Implementing and publishing the API

. On the *Choose operation* screen click *Greet with name* to open the *Integration Flow Editor*.

. The left hand side of the *Integration Flow Editor* lists the steps in your *Integration*. Click the *Blue Plus Icon* in the center of the flow and choose *Add Connection*.

. Select your *Greeting Slack Target*.

. When prompted to *Choose an action* select *Channel*. You can use this to send a mesasge to a specific channel in your Slack workspace.

. Use the *Channel* dropdown to select the *low-code-project* channel and click *Done*.
The left hand side of the *Integration Flow Editor* should now list your Slack connection with a *Data Type Mismatch* warning. 

.Click the *Warning Icon* and choose *Add a data mapping step*.

. From the *Configure Mapper* screen click the *body* element in the *Source* panel to expand it.

. Click the *name* field under the *body*, then click the *message* element in the *Target* panel. This maps the value of the incoming HTTP request *body* to the outgoing Slack *message* property.

. In the right hand *Mapping Details* panel click the *Arrow Icon* under the *Targets* section to add a transformation.

. Using the dropdown change the transformation type from *Append* to *Prepend*.

. Enter the following in the *string* field under the dropdown:
+
----
Hello from 
----

. Click *Done*.

. Click *Publish* to trigger an link:https://docs.openshift.com/container-platform/3.11/creating_images/s2i.html[Source to Image (S2I), window="_blank"] build.

. Wait until Fuse Online reports your deployment was successful.

[type=verification]
Does the Fuse Online *Home* screen list your *greeting api* with a blue box that contains the text *Running*?


[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.



[time=5]
== Exposing and invoking the API

=== API Management Login

// TODO service & url placeholders
. Open the link:{api-management-url}[{3Scale-ProductName} Login screen, window="_blank"].

. Select the *Red Hat Single Sign On* option. This triggers an OAuth Flow and redirects you back to the {3Scale-ProductName} Dashboard.

. Dismiss the *How does 3Scale work?* option which is displayed the first time you log in to {3Scale-ProductName}. The main Dashboard is displayed.

[type=verification]
Can you see the {3Scale-ProductName} Dashboard and navigate the main menu?

[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.


=== Adding the Fuse Aggregation App Endpoint to Red Hat 3scale

. From the *Dashboard*, select the *New API* item.
. Select the *Import from Dashboard* option.
If this option is not enabled, click *authenticate with OpenShift* to enable the option.

. Choose the 'fuse' option from the *Namespace* list.
. Choose 'i-greeting-api' from the *Name* list.
. Click *Create Service*.
The 3scale dashboard is displayed, with notification: `The service will be imported shortly. You will receive a notification when it is done.`
[type=verification]
Is the API service available?
You might encounter a *403: Authentication failed* message. You can ignore this message, the issue is resolved in a later step.

[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.



=== Invoking the API

. Use an HTTP client to invoke the route.

[type=verification]
Did the message "Hello from $YOUR_NAME" appear in your Slack channel?

[type=verificationFail]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.



